### ISSUE TITLE
Changing Licence From AGPL to MIT

### ISSUE THREAD

**Issue by mentalrob** [AR-Development/PersistentEmpires-OpenSourced#57]
AGPL is very restrictive about distributing the code and enforces if any type of dependency to the PE should be open sourced. Thus making it hard to monetize and compete with others.

MIT allows you to basically do anything, you can create your own closed source copies, distribute them and make money on them.

I don't want to change the licencing on my own but i want your opinions @ianespana @Heavybob @Snah79 @lenggiauit @ErraynGit

**Comment by haliliceylan** [comment]
I do not agree with converting to MIT, as there are many people who have contributed significantly to this project. If it makes sense, the team can provide an alternative license connected to Patreon. However, if no payment is made and no Patreon tier is selected, developers/server owner must comply with the APGL license.

By supporting the project on Patreon, they can access a special license that allows for closed-source usage. There can be different Patreon tiers for different plans, so you can choose the one that best fits your needs. This way, you help sustain the project while getting the flexibility you need for your proprietary applications.

Examples: Minio, MongoDB
